### ISSUE TITLE
rdesktop failed - Unable to install package NoMachine server

### ISSUE THREAD

**Issue by guyostfeld** [isaac-sim/IsaacAutomator#15]
Hi!
after am following the instructions and running ./run_aws
I got the following error: TASK [rdesktop : Install NoMachine server] ************************************************
fatal: [3.217.177.181]: FAILED! => {"changed": false, "msg": "Unable to install package: E:Invalid archive signature"}

that seems to be the only failure: PLAY RECAP ***********************************************************************
              : ok=73   changed=58   unreachable=0    failed=1    skipped=28   rescued=0    ignored=0

**Comment by myurasov-nv** [comment]
Is this persistent (eg did retry help)? To try once again you can run `./repair -T <deployment_name>` command.

**Comment by guyostfeld** [comment]
thanks trying that now

**Comment by guyostfeld** [comment]
yes the same error

**Comment by myurasov-nv** [comment]
Please check out `v3.2.1` for the fix. (`git checkout v3.2.1`). Thanks for reporting!
