### ISSUE TITLE
Issue on Google Cloud Deployment

### ISSUE THREAD

**Issue by smash0190** [isaac-sim/IsaacAutomator#17]
Hi,
There are a couple of issues for google cloud deployment. The nvidia grid driver doesn't build:
1. 
gcc-12 
is not installed and the driver wants gcc-12.
apt install gcc-12 fixes that
2. The driver doesn't compile
See attached log.

Here is the command I used for to deploy:

./deploy-gcp --ngc-api-key KEY  --project PROJECTNAME --deployment-name test-issacsim --isaac  --isaac-gpu-count 1 --isaac-instance-type g2-standard-8 --isaac-image nvcr.io/nvidia/isaac-sim:4.1.0 --vnc-password ASDFASDF --zone us-east1-d --oige no --isaaclab v1.1.0

Error message:

o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/nv-memdbg.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/nv-ibmnpu.o /t
mp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/nv-report-err.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/nv-rsync.o /tm
p/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kerne
   l/nvidia/nv-msi.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/nv-caps.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvid
ia/nv-frontend.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/nv_uvm_interface.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel
/nvidia/libspdm_aead.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/libspdm_ecc.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kerne
l/nvidia/libspdm_hkdf.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/libspdm_rand.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/ker
nel/nvidia/libspdm_shash.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/libspdm_aead_aes_gcm.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.
03-grid/kernel/nvidia/libspdm_sha.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/libspdm_hmac_sha.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535
.129.03-grid/kernel/nvidia/libspdm_hkdf_sha.o /tmp/self
   gz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/libspdm_ec.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/libspdm_x509.o /tmp/s
elfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/nvlink_linux.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/nvlink_caps.o /tmp/
selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/linux_nvswitch.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/procfs_nvswitch.
o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia/i2c_nvswitch.o
   ld -r -o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia-modeset/nv-modeset-interface.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia-modeset/nvidia-modeset-linux.o /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia-modeset/nv-kthread-q.o
     LD [M]  /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/nvidia-peermem.o
   make[3]: Target '/tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel/' not remade because of errors.
   make[2]: *** [/usr/src/linux-headers-6.8.0-1015-gcp/Makefile:1925: /tmp/selfgz45339/NVIDIA-Linux-x86_64-535.129.03-grid/kernel] Error 2
   make[2]: Target 'modules' not remade because of errors.
   make[1]: *** [Makefile:240: __sub-make] Error 2
   make[1]: Target 'modules' not remade because of errors.
   make[1]: Leaving directory '/usr/src/linux-headers-6.8.0-1015-gcp'
   make: *** [Makefile:82: modules] Error 2
-> Error.
ERROR: An error occurred while performing the step: "Building kernel modules". See /var/log/nvidia-installer.log for details.
-> The command `cd ./kernel; /usr/bin/make -k -j8  NV_EXCLUDE_KERNEL_MODULES="" SYSSRC="/lib/modules/6.8.0-1015-gcp/build" SYSOUT="/lib/modules/6.8.0-1015-gcp/build" ` failed with the following output:

**Comment by myurasov-nv** [comment]
Hello, thanks for reporting! The issue should be fixed in v3.4.0.
